# typed: false
# frozen_string_literal: true

# This file was generated by moshi-hook's release script. DO NOT EDIT.
class MoshiHook < Formula
  desc "Portable daemon + CLI that bridges AI coding agents to the Moshi mobile app"
  homepage "https://getmoshi.app"
  version "0.3.30"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cdn.getmoshi.app/hook/v0.3.30/moshi-hook_Darwin_x86_64.tar.gz"
      sha256 "1693b52079ca698f22968a3c25b41e47b6f758ddbbfe299cb1cc2438a0ff46a4"

      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
    if Hardware::CPU.arm?
      url "https://cdn.getmoshi.app/hook/v0.3.30/moshi-hook_Darwin_arm64.tar.gz"
      sha256 "1591fc2293376667c1c6d4eb6d86b4e1474ddee329dcb7948e1b52824daf1e76"

      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cdn.getmoshi.app/hook/v0.3.30/moshi-hook_Linux_x86_64.tar.gz"
      sha256 "9342d329b5bf3c184fa5fb1b9c0f7e29528addb1e59574191d208b5e67ad247c"
      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cdn.getmoshi.app/hook/v0.3.30/moshi-hook_Linux_arm64.tar.gz"
      sha256 "ca3ebdb914745075462be3bcddaaeeab15ca959556f6c9ab4da230117396c9d6"
      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
  end

  def caveats
    <<~EOS
      moshi-hook is a daemon. Start it with:
        moshi-hook pair --token $MOSHI_PAIRING_TOKEN
        moshi-hook install
        brew services start moshi-hook
    EOS
  end

  service do
    run [opt_bin/"moshi-hook", "serve"]
    keep_alive true
    log_path var/"log/moshi-hook.log"
    error_log_path var/"log/moshi-hook.log"
    working_dir var
  end

  test do
    assert_match "moshi-hook", shell_output("#{bin}/moshi-hook version")
    assert_match "moshi-hook", shell_output("#{bin}/moshi version")
  end
end
