# typed: false
# frozen_string_literal: true

# This file was generated by moshi-hook's release script. DO NOT EDIT.
class MoshiHook < Formula
  desc "Portable daemon + CLI that bridges AI coding agents to the Moshi mobile app"
  homepage "https://getmoshi.app"
  version "0.2.75"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cdn.getmoshi.app/hook/v0.2.75/moshi-hook_Darwin_x86_64.tar.gz"
      sha256 "a7c48c233695b990449fa4d39c3f9c0f8a25f2b4e9ad79b5adae72452f2c6b8b"

      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
    if Hardware::CPU.arm?
      url "https://cdn.getmoshi.app/hook/v0.2.75/moshi-hook_Darwin_arm64.tar.gz"
      sha256 "3d3c6f1c1bec7eeeb7911b409a7c796209971782c97d7146ce57ad26bf1df7ae"

      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cdn.getmoshi.app/hook/v0.2.75/moshi-hook_Linux_x86_64.tar.gz"
      sha256 "79b6753f133370fdaf143c423c49d0e854e9d0627c4e5106b72e3656b3ac5390"
      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cdn.getmoshi.app/hook/v0.2.75/moshi-hook_Linux_arm64.tar.gz"
      sha256 "90a590f669b61a76c2291ff209ab987760caf5525bddec34d48a134ccb7f3ca8"
      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
  end

  def caveats
    <<~EOS
      moshi-hook is a daemon. Start it with:
        moshi-hook pair --token $MOSHI_PAIRING_TOKEN
        moshi-hook install
        brew services start moshi-hook
    EOS
  end

  service do
    run [opt_bin/"moshi-hook", "serve"]
    keep_alive true
    log_path var/"log/moshi-hook.log"
    error_log_path var/"log/moshi-hook.log"
    working_dir var
  end

  test do
    assert_match "moshi-hook", shell_output("#{bin}/moshi-hook version")
    assert_match "moshi-hook", shell_output("#{bin}/moshi version")
  end
end
