# typed: false
# frozen_string_literal: true

# This file was generated by moshi-hook's release script. DO NOT EDIT.
class MoshiHook < Formula
  desc "Portable daemon + CLI that bridges AI coding agents to the Moshi mobile app"
  homepage "https://getmoshi.app"
  version "0.2.72"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cdn.getmoshi.app/hook/v0.2.72/moshi-hook_Darwin_x86_64.tar.gz"
      sha256 "d76fe173b2bb4c183272905b62bd0be7c7af631ac70d0a4c457509633dd1735e"

      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
    if Hardware::CPU.arm?
      url "https://cdn.getmoshi.app/hook/v0.2.72/moshi-hook_Darwin_arm64.tar.gz"
      sha256 "0b1cf0e562eea0251843d334479194f2c295ce97163d2099013fd34a95b10117"

      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cdn.getmoshi.app/hook/v0.2.72/moshi-hook_Linux_x86_64.tar.gz"
      sha256 "3d464acfd121b5f0162f164500d92ff3050ca01e93515f58632db258ed2eb8cd"
      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cdn.getmoshi.app/hook/v0.2.72/moshi-hook_Linux_arm64.tar.gz"
      sha256 "23de526fd680ea4e1e7d19b6e41baa0767c1656b02bdf0f019cfb54c78fa4114"
      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
  end

  def caveats
    <<~EOS
      moshi-hook is a daemon. Start it with:
        moshi-hook pair --token $MOSHI_PAIRING_TOKEN
        moshi-hook install
        brew services start moshi-hook
    EOS
  end

  service do
    run [opt_bin/"moshi-hook", "serve"]
    keep_alive true
    log_path var/"log/moshi-hook.log"
    error_log_path var/"log/moshi-hook.log"
    working_dir var
  end

  test do
    assert_match "moshi-hook", shell_output("#{bin}/moshi-hook version")
    assert_match "moshi-hook", shell_output("#{bin}/moshi version")
  end
end
